kind: pipeline
type: kubernetes
name: dmellis-neptune
platform:
  os: linux
  arch: arm64
workspace: /neptune
steps:
  - name: build for test
    image: plugins/docker
    settings:
      repo: docker.dmellis.com/dmellis/neptune
      registry: docker.dmellis.com
      dockerfile: ./Dockerfile
      tags: ["${DRONE_COMMIT_SHA:0:7}", "latest"]
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
    when:
      event:
        exclude:
          - tag
  - name: build for production
    image: plugins/docker
    settings:
      repo: docker.dmellis.com/dmellis/neptune
      registry: docker.dmellis.com
      dockerfile: ./Dockerfile
      tags: ["${DRONE_COMMIT_SHA:0:7}", "latest", "${DRONE_TAG}"]
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
    when:
        event:
          - tag
trigger:
  event:
    - cron
    - push
    - pull_request
    - tag